### ISSUE TITLE
Automatically install required system images.

### ISSUE THREAD

**Issue by dwb357** [mfuchs/android-emulators-gradle#6]
This becomes much more useful in CI environments (probably the only real reason it needs to exist at all) if it has the ability to automatically install any needed system images via sdkmanager.

Even better would be if it could automatically install the Android SDK itself, but that's asking a lot.

**Comment by mfuchs** [comment]
This can already be done with some caveats see https://github.com/Catrobat/Gradle#basic-emulator-managment and the install part.

Yet in my experience it turned out to be easier to create docker images with all the dependencies manually.
The issue was of how to cache the Android SDK on the CI without race conditions.
We used the Lockable Resources Jenkins plugin for that, yet at the same time this moves complexity to the jobs themselves.
